---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repo-feed-secrets
  namespace: apps
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: repo-feed-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
  data:
    - secretKey: DRIFT__DATABASE__URL
      remoteRef:
        key: srvc-drift
        property: postgres_url
    - secretKey: DRIFT__DISCORD__WEBHOOK_URL
      remoteRef:
        key: srvc-drift
        property: discord_webhook_url
    - secretKey: DRIFT__QDRANT__API_KEY
      remoteRef:
        key: srvc-drift
        property: qdrant_api_key

