apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capacitor-tls
  namespace: flux-system
spec:
  secretName: capacitor-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - capacitor.internal.newsbro.cc
