apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: capacitor
  namespace: flux-system
  labels:
    app: capacitor
spec:
  ingressClassName: private 
  rules:
    - host: capacitor.internal.newsbro.cc 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: capacitor-next
                port:
                  number: 80
