---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: capacitor-next
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/gimlet-io/charts/capacitor-next
  ref:
    semver: "2025.11.2"
  secretRef:
    name: ghcr-auth
