apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: capacitor-next
  namespace: capacitor
spec:
  refreshInterval: 10m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: capacitor-next
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: capacitor
