apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: capacitor-next
  namespace: flux-system
spec:
  refreshInterval: 10m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: capacitor-next
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
  dataFrom:
    - secretKey: LICENSE_KEY
      remoteRef:
        key: capacitor-next
        property: api-key
