apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redisinsight
  namespace: redis
  labels:
    app: redisinsight
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
spec:
  ingressClassName: private
  
  tls:
    - hosts:
        - redis.internal.newsbro.cc
      secretName: redis-tls

  rules:
    - host: redis.internal.newsbro.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redisinsight-service
                port:
                  number: 80
