apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qdrant-tls
  namespace: qdrant
spec:
  secretName: qdrant-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - qdrant.internal.newsbro.cc
