apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: repo-article
  namespace: apps
  labels:
    app: repo-article
  annotations:
    nginx.ingress.kubernetes.io/limit-rpm: "100"
    nginx.ingress.kubernetes.io/limit-burst: "50"
    cert-manager.io/cluster-issuer: letsencrypt-dns01
spec:
  ingressClassName: public
  
  tls:
    - hosts:
        - article.newsbro.cc
      secretName: newsbro-wildcard-tls

  rules:
    - host: article.newsbro.cc
      http:
        paths:
          - path: /api/v1/article
            pathType: Prefix
            backend:
              service:
                name: repo-article 
                port:
                  number: 80
          - path: /api/v1/feedback
            pathType: Prefix
            backend:
              service:
                name: repo-article 
                port:
                  number: 80
          - path: /api/v1/rss
            pathType: Prefix
            backend:
              service:
                name: repo-article 
                port:
                  number: 80