apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repo-article-secrets
  namespace: apps
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: repo-article-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
  data:
    - secretKey: DATABASE_USERNAME
      remoteRef:
        key: repo-article/postgres
        property: username
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: repo-article/postgres
        property: password
    - secretKey: JWT_SECRET
      remoteRef:
        key: oidc
        property: JWT_SECRET
