apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console
  namespace: minio
  labels:
    app: minio
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    nginx.ingress.kubernetes.io/proxy-body-size: "5G"
spec:
  ingressClassName: private

  tls:
    - hosts:
        - minio.internal.newsbro.cc
      secretName: newsbro-wildcard-tls

  rules:
    - host: minio.internal.newsbro.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-new-console
                port:
                  number: 9001
