---
# https://fluxcd.io/flux/components/helm/helmreleases/
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio-new
  namespace: minio
spec:
  interval: 10m0s
  chart:
    spec:
      chart: minio
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: helm-repo
        namespace: minio
  driftDetection:
    mode: enabled
  upgrade:
    crds: CreateReplace
  values:
    # https://artifacthub.io/packages/helm/bitnami/minio?modal=values
    auth:
      existingSecret: minio-new
      rootUserSecretKey: rootUser
      rootPasswordSecretKey: rootPassword
      forcePassword: true # force update on vault rotation
      useSecret: true

    usersExistingSecrets:
      - centralized-minio-users

    persistence:
      enabled: true
      size: 20Gi
      storageClass: local-path

    replicas: 2
    drivesPerNode: 1

    minioAPIPort: 9000
    minioConsolePort: 9001
    service:
      type: ClusterIP
      port: 9000
    consoleService:
      type: ClusterIP
      port: 9001

    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: 500m

    priorityClassName: "critical-resilient"

    securityContext:
      enabled: false

    mode: distributed

    buckets:
      - name: mlflow
        policy: none
        purge: false

    ingress:
      enabled: false

    consoleIngress:
      enabled: false
