# https://fluxcd.io/flux/components/source/helmrepositories/
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: helm-repo-operator
  namespace: redis
spec:
  interval: 10m0s
  type: default
  url: https://spotahome.github.io/redis-operator
  provider: generic
