---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-vault-check
  namespace: datadog
data:
  vault.yaml: |
    init_config:
    instances:
      - api_url: http://vault.vault.svc.cluster.local:8200/v1
        auth_method: kubernetes
        kubernetes_role: datadog-agent
        kubernetes_auth_path: auth/kubernetes/login
