apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: datadog-secret
  namespace: datadog
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: datadog-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
      data:
        api-key: "{{ .api_key }}"
        app-key: "{{ .app_key }}"
  dataFrom:
    - extract:
        key: datadog
