---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srvc-inference-tfidf
  namespace: apps
  labels:
    app: srvc-inference-tfidf
    type: backends
    model: tfidf
spec:
  # replicas: 1 # managed by hpa
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: srvc-inference-tfidf
  template:
    metadata:
      labels:
        app: srvc-inference-tfidf
        monitoring: "enabled"
    spec:
      imagePullSecrets:
        - name: pull-secret
      containers:
        - name: srvc-inference-tfidf
          image: ghcr.io/therayquaza/newsbro/srvc-inference:srvc-inference-tf_idf-v1.0.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: srvc-inference-tfidf-config
            - configMapRef:
                name: postgres-config
            - configMapRef:
                name: kafka-config
            - configMapRef:
                name: redis-config
            - configMapRef:
                name: qdrant-config
            - configMapRef:
                name: oidc-config
            - secretRef:
                name: srvc-inference-tfidf-secrets
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 15
            failureThreshold: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 180
            periodSeconds: 15
            failureThreshold: 10
            timeoutSeconds: 5
