kind: Service
apiVersion: v1
metadata:
  name: srvc-inference-tfidf
  namespace: apps
  labels:
    app: srvc-inference-tfidf
spec:
  type: ClusterIP
  selector:
    app: srvc-inference-tfidf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
