apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: new-articles-command
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  topicName: new-articles-command
  partitions: 2
  replicas: 2
  config:
    retention.ms: 3600000 # 1h
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: article-aggregate
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  topicName: article-aggregate
  partitions: 1
  replicas: 2
  config:
    retention.ms: 864000000 # 10 days
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: rss-aggregate
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  topicName: rss-aggregate
  partitions: 1
  replicas: 2
  config:
    retention.ms: 864000000 # 10 days
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: feedback-aggregate
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  topicName: feedback-aggregate
  partitions: 3
  replicas: 2
  config:
    retention.ms: 86400000 # 1 day
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: account-aggregate
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  topicName: account-aggregate
  partitions: 1
  replicas: 2
  config:
    retention.ms: 864000000 # 10 days
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: inference-command
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  topicName: inference-command
  partitions: 3
  replicas: 2
  config:
    retention.ms: 86400000 # 1 day
    segment.bytes: 1073741824
