---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  secretRef:
    name: discord-webhook-alert
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook-alert
  namespace: flux-system
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: discord-webhook-alert
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        address: "{{ .webhook_url }}"
  dataFrom:
    - extract:
        key: discord/flux
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: discord-info
  namespace: flux-system
spec:
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: "*"
      namespace: "*"
    - kind: Kustomization
      name: "*"
      namespace: "*"
    - kind: GitRepository
      name: "*"
      namespace: "*"
  providerRef:
    name: discord
  eventMetadata:
    summary: "FluxCD Info: {{ .Reason }} on {{ .Kind }}/{{ .Name }}"
    description: |
      Resource: {{ .Kind }}/{{ .Name }}
      Namespace: {{ .Namespace }}
      Reason: {{ .Reason }}
      Message: {{ .Message }}
      Time: {{ .Timestamp }}
