---
kind: Service
apiVersion: v1
metadata:
  name: srvc-inference-sbert
  namespace: apps
  labels:
    app: srvc-inference-sbert
spec:
  type: ClusterIP
  selector:
    app: srvc-inference-sbert
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
