---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: apps
spec:
  interval: 10m
  path: ./k8s/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
  - name: ingress-nginx
    namespace: flux-system
  - name: minio
    namespace: minio
  - name: redis
    namespace: flux-system
  - name: qdrant
    namespace: flux-system
  - name: kafka
    namespace: flux-system
  - name: mlflow
    namespace: mlflow
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: port-front
    namespace: apps
  - apiVersion: apps/v1
    kind: Deployment
    namespace: apps
    name: repo-account
  - apiVersion: apps/v1
    kind: Deployment
    namespace: apps
    name: repo-article
  - apiVersion: apps/v1
    kind: Deployment
    namespace: apps
    name: repo-feed
  - apiVersion: batch/v1
    kind: CronJob
    namespace: apps
    name: srvc-scrapping-job
  - apiVersion: apps/v1
    kind: Deployment
    namespace: apps
    name: srvc-inference-sbert
  - apiVersion: apps/v1
    kind: Deployment
    namespace: apps
    name: srvc-inference-tfidf
