---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: datadog-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/datadog/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: datadog-agent
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/datadog/agent
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
  - name: datadog-operator
  # healthChecks:
  # - apiVersion: datadoghq.com/v1alpha1
  #   kind: DatadogAgent
  #   name: datadog-agent
  #   namespace: datadog
