apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: datadog-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/datadog/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: external-secrets
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: datadog-operator
      namespace: datadog
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: datadog-agent
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/datadog/agent
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: datadog-operator
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: datadog-agent-agent
      namespace: datadog
    - apiVersion: apps/v1
      kind: Deployment
      name: datadog-agent-cluster-agent
      namespace: datadog
