apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: metallb
    - name: cert-manager
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: ingress-nginx-private-controller
      namespace: ingress-nginx
    - apiVersion: apps/v1
      kind: Deployment
      name: ingress-nginx-public-controller
      namespace: ingress-nginx
