---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/kafka
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
