apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - minio.yaml
  - capacitor.yaml
  - postgres.yaml
  - mlflow.yaml
  - redis.yaml
  - qdrant.yaml
  - apps.yaml
  - external-secrets.yaml
  - vault.yaml
  - cert-manager.yaml
  - kafka.yaml
  - ingress-nginx.yaml
  - metallb.yaml
  - datadog.yaml
