---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
  - apiVersion: apps/v1
    kind: DaemonSet
    name: metallb-speaker
    namespace: metallb-system
  - apiVersion: apps/v1
    kind: Deployment
    name: metallb-controller
    namespace: metallb-system
