---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mlflow
  namespace: mlflow
spec:
  interval: 10m
  path: ./k8s/mlflow
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: mlflow
    namespace: mlflow
  - apiVersion: v1
    kind: Service
    name: mlflow
    namespace: mlflow
  dependsOn:
  - name: minio
    namespace: minio
  - name: postgres
    namespace: postgres
