apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka-operator
  namespace: kafka
  labels:
    app: kafka-operator
spec:
  releaseName: kafka-operator
  interval: 10m0s
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.49.0
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: kafka
  driftDetection:
    mode: enabled
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 5m0s
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 5m0s
    remediation:
      retries: 3
  values:
    watchAnyNamespace: true
    tolerations: []
    resources:
      limits:
        memory: 384Mi
        cpu: 1000m
      requests:
        memory: 384Mi
        cpu: 200m
    securityContext:
      runAsNonRoot: true
      runAsUser: 1006
      fsGroup: 2006
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
    podSecurityContext:
      fsGroup: 2006
      runAsUser: 1006
      runAsGroup: 3006
      fsGroupChangePolicy: OnRootMismatch
    podAnnotations:
      ad.datadoghq.com/strimzi-cluster-operator.checks: |
        {
          "strimzi": {
            "instances":[
              {
                "cluster_operator_endpoint": "http://%%host%%:8080/metrics"
              }
            ]
          }
        }
    extraEnvs:
      - name: STRIMZI_KUBERNETES_VERSION
        value: "major=1,minor=33"
