---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-db-secret
  namespace: postgres
  annotations:
    cnpg.io/rotate-password: "true"
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: mlflow-db-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: mlflow/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: mlflow/postgres
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repo-account-db-secret
  namespace: postgres
  annotations:
    cnpg.io/rotate-password: "true"
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: repo-account-db-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: repo-account/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: repo-account/postgres
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repo-article-db-secret
  namespace: postgres
  annotations:
    cnpg.io/rotate-password: "true"
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: repo-article-db-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: repo-article/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: repo-article/postgres
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: admin-db-secret
  namespace: postgres
  annotations:
    cnpg.io/rotate-password: "true"
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: admin-db-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: postgres/admin
        property: username
    - secretKey: password
      remoteRef:
        key: postgres/admin
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: srvc-scrapping-db-secret
  namespace: postgres
  annotations:
    cnpg.io/rotate-password: "true"
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: srvc-scrapping-db-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: srvc-scrapping/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: srvc-scrapping/postgres
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: srvc-drift-db-secret
  namespace: postgres
  annotations:
    cnpg.io/rotate-password: "true"
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: srvc-drift-db-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: srvc-drift/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: srvc-drift/postgres
        property: password
