---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: mlflow-db
  namespace: postgres
spec:
  cluster:
    name: postgres-cluster
  name: mlflow
  owner: mlflow
  ensure: present
  extensions: []
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: repo-account-db
  namespace: postgres
spec:
  cluster:
    name: postgres-cluster
  name: repo-account
  owner: repo-account
  ensure: present
  extensions: []
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: repo-article-db
  namespace: postgres
spec:
  cluster:
    name: postgres-cluster
  name: repo-article
  owner: repo-article
  ensure: present
  extensions: []
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: srvc-scrapping-db
  namespace: postgres
spec:
  cluster:
    name: postgres-cluster
  name: srvc-scrapping
  owner: srvc-scrapping
  ensure: present
  extensions: []
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: srvc-drift-db
  namespace: postgres
spec:
  cluster:
    name: postgres-cluster
  name: srvc-drift
  owner: srvc-drift
  ensure: present
  extensions: []
