# https://fluxcd.io/flux/components/source/helmrepositories/
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: helm-repo
  namespace: postgres
spec:
  interval: 10m0s
  type: default
  url: https://cloudnative-pg.github.io/charts
  provider: generic
