apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mlflow-tls
  namespace: mlflow
spec:
  secretName: mlflow-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - mlflow.internal.newsbro.cc
