apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: newsbro-wildcard-tls
  namespace: app
spec:
  secretName: newsbro-apps-tls
  issuerRef:
    name: letsencrypt-dns01
    kind: ClusterIssuer
  dnsNames:
    - app.newsbro.cc
    - account.newsbro.cc
    - article.newsbro.cc
    - feed.newsbro.cc
    - capacitor.internal.newsbro.cc
    - redpanda.internal.newsbro.cc
    - minio.internal.newsbro.cc
    - redis.internal.newsbro.cc
    - mlflow.internal.newsbro.cc
    - vault.internal.newsbro.cc
    # add more for each service
