apiVersion: v1
kind: ServiceAccount
metadata:
  name: apps
  namespace: apps
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: newsbro
  name: newsbro-reader
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: newsbro-reader-binding
  namespace: newsbro
subjects:
- kind: ServiceAccount
  name: apps
  namespace: apps
roleRef:
  kind: Role
  name: newsbro-reader
  apiGroup: rbac.authorization.k8s.io
