apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- repo.yaml
- vault.yaml
- ingress.yaml
- service-account.yaml
- cluster-role-binding.yaml
- vault-auth-token.yaml
