---
# https://fluxcd.io/flux/components/source/helmrepositories/
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: helm-repo
  namespace: ingress-nginx
spec:
  interval: 10m0s
  type: oci
  url: oci://ghcr.io/nginx/charts/nginx-ingress
  provider: generic
