apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx-private
  namespace: ingress-nginx
spec:
  interval: 10m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.14.0
      sourceRef:
        kind: HelmRepository
        name: helm-repo
        namespace: ingress-nginx
  driftDetection:
    mode: enabled
  upgrade:
    crds: CreateReplace
  values:
    controller:
      watchIngressWithoutClass: false
      electionID: ingress-controller-private-leader
      ingressClass:
        name: private
        create: true
        setAsDefaultIngress: false
        controllerValue: "k8s.io/ingress-nginx-private"
      ingressClassResource:
        name: private
        enabled: true
        controllerValue: "k8s.io/ingress-nginx-private"
        default: false
      service:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        loadBalancerIP: 10.0.0.1
        annotations:
          metallb.io/address-pool: private-pool
        ports:
          http: 80
          https: 443
      priorityClassName: "critical-resilient"


      hostNetwork: false
      replicaCount: 2
      logLevel: info

      podSecurityContext:
        fsGroup: 3005
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault

      containerSecurityContext:
        runAsUser: 1005
        runAsGroup: 2005
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        privileged: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
              app.kubernetes.io/instance: ingress-nginx-private
              app.kubernetes.io/component: controller

      podLabels:
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/instance: ingress-nginx-private
        app.kubernetes.io/component: controller

      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 500m
