apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx-public
  namespace: ingress-nginx
spec:
  interval: 10m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.14.0
      sourceRef:
        kind: HelmRepository
        name: helm-repo
        namespace: ingress-nginx
  driftDetection:
    mode: enabled
  upgrade:
    crds: CreateReplace
  values:
    controller:
      watchIngressWithoutClass: true
      electionID: ingress-controller-public-leader
      ingressClass:
        name: public
        create: true
        setAsDefaultIngress: true
        controllerValue: "k8s.io/ingress-nginx-public"
      ingressClassResource:
        name: public
        enabled: true
        controllerValue: "k8s.io/ingress-nginx-public"
        default: true
      service:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        loadBalancerIP: 192.168.0.18
        annotations:
          metallb.io/address-pool: public-pool
        ports:
          http: 80
          https: 443
      priorityClassName: "critical-resilient"

      hostNetwork: false
      replicaCount: 2
      logLevel: info

      podSecurityContext:
        fsGroup: 3004
        seccompProfile:
          type: RuntimeDefault
        fsGroupChangePolicy: OnRootMismatch

      containerSecurityContext:
        runAsUser: 1004
        runAsGroup: 2004
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        privileged: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
              app.kubernetes.io/instance: ingress-nginx-public
              app.kubernetes.io/component: controller

      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 500m
