apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx-public
  namespace: ingress-nginx
spec:
  interval: 10m0s
  chart:
    spec:
      chart: ingress-nginx
      version: 4.14.0
      sourceRef:
        kind: HelmRepository
        name: helm-repo
        namespace: ingress-nginx
  values:
    controller:
      ingressClass:
        name: public
        create: true
        setAsDefaultIngress: true
      service:
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: 192.168.0.10 # home lan
      replicaCount: 2
      logLevel: info
      watchNamespace: ""
    serviceAccount:
      create: true
    enableCustomResources: true
