apiVersion: v1
kind: ConfigMap
metadata:
  name: port-front-config
  namespace: apps
data:
  ACCOUNT_BASE_URL: https://account.newsbro.cc
  ARTICLE_BASE_URL: https://article.newsbro.cc
  FEED_BASE_URL: https://feed.newsbro.cc
