apiVersion: apps/v1
kind: Deployment
metadata:
  name: port-front
  namespace: apps
  labels:
    app: port-front
    type: frontends
spec:
  # replicas: 1 # managed by hpa
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: port-front
  template:
    metadata:
      labels:
        app: port-front
    spec:
      imagePullSecrets:
        - name: pull-secret
      containers:
        - name: port-front
          image: ghcr.io/therayquaza/newsbro/port-front:port-front-v1.4.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - configMapRef:
                name: port-front-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "125m"
            limits:
              memory: "1Gi"
              cpu: "250m"
          healthProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
