apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: port-front
  namespace: apps
  labels:
    app: port-front
  annotations:
    nginx.ingress.kubernetes.io/limit-rpm: "300"
    nginx.ingress.kubernetes.io/limit-burst: "100"
    
    cert-manager.io/cluster-issuer: letsencrypt-dns01
spec:
  ingressClassName: public
  
  tls:
    - hosts:
        - app.newsbro.cc
      secretName: newsbro-wildcard-tls

  rules:
    - host: app.newsbro.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: port-front
                port:
                  number: 80
