apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-feed
  namespace: apps
  labels:
    app: repo-feed
    type: backends
spec:
  # replicas: 1 # managed by hpa
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      app: repo-feed
  template:
    metadata:
      labels:
        app: repo-feed
        monitoring: "enabled"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090" 
    spec:
      imagePullSecrets:
        - name: pull-secret
      containers:
        - name: repo-feed
          image: ghcr.io/therayquaza/newsbro/repo-feed:repo-feed-v1.1.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9090
              name: metrics
          envFrom:
            - configMapRef:
                name: repo-feed-config
            - configMapRef:
                name: redis-config # Redis master and sentinels
            - configMapRef:
                name: kafka-config
            - configMapRef:
                name: oidc-config
            - secretRef:
                name: repo-feed-secrets # Redis creds
            - secretRef:
                name: oidc-secrets # JWT
          resources:
            requests:
              memory: "256Mi"
              cpu: "125m"
            limits:
              memory: "1Gi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
