apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: repo-feed
  namespace: apps
  labels:
    app: repo-feed
  annotations:
    nginx.ingress.kubernetes.io/limit-rpm: "100"
    nginx.ingress.kubernetes.io/limit-burst: "50"
    cert-manager.io/cluster-issuer: letsencrypt-dns01
spec:
  ingressClassName: public

  tls:
    - hosts:
        - feed.newsbro.cc
      secretName: newsbro-wildcard-tls

  rules:
    - host: feed.newsbro.cc
      http:
        paths:
          - path: /api/v1/feed
            pathType: Prefix
            backend:
              service:
                name: repo-feed
                port:
                  number: 80
