apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repo-feed-secrets
  namespace: apps
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: repo-feed-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: repo-feed/redis
        property: password
    - secretKey: REDIS_DB
      remoteRef:
        key: repo-feed/redis
        property: db
